// Powered by OnSpace.AI
// Rich mock data for V1.0 development and demonstration

import { Goal, Action, WeeklyReflection, UserProfile, ConsistencyStats } from '@/types';

const today = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const daysFromNow = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return fmt(d);
};

export const MOCK_USER: UserProfile = {
  id: 'user-1',
  name: 'Alex Carter',
  email: 'alex@example.com',
  mainObjective: 'Build a healthier, more skilled version of myself',
  preferences: {
    preferredTime: 'morning',
    preferredDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    progressStyle: 'detailed',
    weeklyTarget: 5,
    reminderEnabled: true,
    reminderTime: '08:00',
  },
  streakDays: 7,
  joinedAt: daysFromNow(-30),
};

export const MOCK_GOALS: Goal[] = [
  {
    id: 'goal-1',
    userId: 'user-1',
    title: 'Improve Physical Fitness',
    description: 'Build a consistent exercise routine and improve overall health',
    why: 'I want more energy and confidence in my daily life',
    category: 'Health',
    priority: 'high',
    status: 'active',
    progressStatus: 'on_track',
    startDate: daysFromNow(-14),
    targetDate: daysFromNow(60),
    routine: {
      frequencyType: 'weekly',
      daysPerWeek: 4,
      preferredDays: ['Monday', 'Wednesday', 'Friday', 'Sunday'],
      preferredTime: '07:00',
      durationMinutes: 45,
    },
    milestones: [
      {
        id: 'ms-1',
        goalId: 'goal-1',
        title: 'Build Cardio Base',
        description: 'Establish a consistent cardio routine',
        targetDate: daysFromNow(20),
        status: 'in_progress',
        actions: [],
        createdAt: daysFromNow(-14),
      },
      {
        id: 'ms-2',
        goalId: 'goal-1',
        title: 'Strength Foundation',
        description: 'Build basic strength across major muscle groups',
        targetDate: daysFromNow(45),
        status: 'pending',
        actions: [],
        createdAt: daysFromNow(-14),
      },
    ],
    actions: [
      {
        id: 'act-1',
        goalId: 'goal-1',
        milestoneId: 'ms-1',
        title: '30-min Morning Run',
        description: 'Easy paced run around the park',
        dueDate: fmt(today),
        preferredTime: '07:00',
        estimatedDurationMinutes: 30,
        frequency: 'weekly',
        priority: 'high',
        status: 'upcoming',
        createdAt: daysFromNow(-2),
        updatedAt: daysFromNow(-2),
      },
      {
        id: 'act-2',
        goalId: 'goal-1',
        milestoneId: 'ms-1',
        title: 'Bodyweight Circuit',
        description: '3 sets of push-ups, squats, lunges',
        dueDate: daysFromNow(2),
        preferredTime: '07:00',
        estimatedDurationMinutes: 45,
        priority: 'medium',
        status: 'upcoming',
        createdAt: daysFromNow(-2),
        updatedAt: daysFromNow(-2),
      },
      {
        id: 'act-3',
        goalId: 'goal-1',
        milestoneId: 'ms-1',
        title: 'Morning Run',
        description: '25 min at moderate pace',
        dueDate: daysFromNow(-3),
        preferredTime: '07:00',
        estimatedDurationMinutes: 25,
        priority: 'high',
        status: 'completed',
        completedAt: daysFromNow(-3),
        createdAt: daysFromNow(-5),
        updatedAt: daysFromNow(-3),
      },
      {
        id: 'act-4',
        goalId: 'goal-1',
        milestoneId: 'ms-1',
        title: 'Stretch & Yoga',
        description: '20 min flexibility work',
        dueDate: daysFromNow(-1),
        preferredTime: '07:00',
        estimatedDurationMinutes: 20,
        priority: 'low',
        status: 'completed',
        completedAt: daysFromNow(-1),
        createdAt: daysFromNow(-3),
        updatedAt: daysFromNow(-1),
      },
    ],
    progressPercent: 38,
    createdAt: daysFromNow(-14),
    updatedAt: daysFromNow(-1),
  },
  {
    id: 'goal-2',
    userId: 'user-1',
    title: 'Learn Spanish',
    description: 'Reach conversational fluency in Spanish within 6 months',
    why: 'I want to travel to Latin America and connect with Spanish-speaking friends',
    category: 'Learning',
    priority: 'high',
    status: 'active',
    progressStatus: 'needs_attention',
    startDate: daysFromNow(-21),
    targetDate: daysFromNow(160),
    routine: {
      frequencyType: 'daily',
      preferredDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      preferredTime: '20:00',
      durationMinutes: 30,
    },
    milestones: [
      {
        id: 'ms-3',
        goalId: 'goal-2',
        title: 'Build Basic Vocabulary',
        description: '500 most common words',
        targetDate: daysFromNow(30),
        status: 'in_progress',
        actions: [],
        createdAt: daysFromNow(-21),
      },
      {
        id: 'ms-4',
        goalId: 'goal-2',
        title: 'Improve Conversation',
        description: 'Hold a 5-min conversation',
        targetDate: daysFromNow(90),
        status: 'pending',
        actions: [],
        createdAt: daysFromNow(-21),
      },
    ],
    actions: [
      {
        id: 'act-5',
        goalId: 'goal-2',
        milestoneId: 'ms-3',
        title: 'Duolingo Lesson',
        description: 'Complete 2 lessons',
        dueDate: fmt(today),
        preferredTime: '20:00',
        estimatedDurationMinutes: 20,
        priority: 'high',
        status: 'upcoming',
        createdAt: daysFromNow(-1),
        updatedAt: daysFromNow(-1),
      },
      {
        id: 'act-6',
        goalId: 'goal-2',
        milestoneId: 'ms-3',
        title: 'Vocabulary Flashcards',
        description: 'Review 20 new words',
        dueDate: daysFromNow(-2),
        preferredTime: '20:00',
        estimatedDurationMinutes: 15,
        priority: 'medium',
        status: 'missed',
        createdAt: daysFromNow(-3),
        updatedAt: daysFromNow(-2),
      },
    ],
    progressPercent: 22,
    createdAt: daysFromNow(-21),
    updatedAt: daysFromNow(-2),
  },
  {
    id: 'goal-3',
    userId: 'user-1',
    title: 'Read 12 Books This Year',
    description: 'One book per month covering fiction, business, and personal growth',
    why: 'Continuous learning keeps my mind sharp',
    category: 'Personal',
    priority: 'medium',
    status: 'active',
    progressStatus: 'ahead',
    startDate: daysFromNow(-60),
    targetDate: daysFromNow(305),
    routine: {
      frequencyType: 'weekly',
      daysPerWeek: 3,
      preferredDays: ['Monday', 'Wednesday', 'Friday'],
      preferredTime: '21:00',
      durationMinutes: 30,
    },
    milestones: [
      {
        id: 'ms-5',
        goalId: 'goal-3',
        title: 'Q1 Reading',
        description: 'Complete first 3 books',
        targetDate: daysFromNow(30),
        status: 'in_progress',
        actions: [],
        createdAt: daysFromNow(-60),
      },
    ],
    actions: [
      {
        id: 'act-7',
        goalId: 'goal-3',
        milestoneId: 'ms-5',
        title: 'Read 30 Minutes',
        description: 'Continue "Atomic Habits"',
        dueDate: fmt(today),
        preferredTime: '21:00',
        estimatedDurationMinutes: 30,
        priority: 'medium',
        status: 'upcoming',
        createdAt: daysFromNow(-1),
        updatedAt: daysFromNow(-1),
      },
    ],
    progressPercent: 58,
    createdAt: daysFromNow(-60),
    updatedAt: daysFromNow(-1),
  },
];

export const MOCK_REFLECTIONS: WeeklyReflection[] = [
  {
    id: 'ref-1',
    userId: 'user-1',
    weekStart: daysFromNow(-7),
    wentWell: 'Completed all workout sessions and felt great energy throughout the week.',
    challenges: 'Spanish practice slipped due to a busy work schedule.',
    improvements: 'Block out 20 minutes each evening specifically for language learning.',
    createdAt: daysFromNow(-1),
  },
];

export const MOCK_CONSISTENCY: ConsistencyStats = {
  currentStreak: 7,
  longestStreak: 12,
  thisWeekCompleted: 4,
  thisWeekPlanned: 6,
  monthlyCompletionRate: 78,
  totalActionsCompleted: 42,
};
